package com.tsu.pring.features.common

const val IMPORT_WORKER_TAG = "IMPORT_WORKER_TAG"
const val COIN_REQUEST_DETERMINANT = "COIN_REQUEST_DETERMINANT"
const val COIN_LIST_DETERMINANT = "COIN_LIST_DETERMINANT"
